apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restapi-db-creds
  namespace: rest-api-namespace
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secretstore
    kind: ClusterSecretStore
  target:
    name: rest-api-secrets
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: secret/restapi        # ✅ logical secret name under mount
        property: user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: secret/restapi
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: secret/restapi
        property: database
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/restapi
        property: database_url
