apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rest-api.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "rest-api.name" . }}
    helm.sh/chart: {{ include "rest-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  PORT: {{ .Values.config.port | quote }}
