{{- if .Values.eso.enabled }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.eso.externalSecretName }}
  namespace: {{ .Values.eso.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "20"

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.eso.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: rest-api-secrets
    # creationPolicy: Merge
  data:
{{- range .Values.eso.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        property: {{ .property }}
{{- end }}
{{- end }}
