{{- if .Values.eso.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.eso.tokenSecret}}
  namespace: {{ .Values.vault.global.namespace}}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
stringData:
  token: "root"
{{- end }}
---


{{- if .Values.eso.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.eso.clusterSecretStoreName }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"

spec:
  provider:
    vault:
      server: "http://rest-api-release-vault.vault-namespace.svc.cluster.local:8200"

      # server: "http://{{ .Values.vault.name }}.svc.cluster.local:8201"
      path: "{{ .Values.eso.vaultPath }}"   # KV mount path only
      version: "v2"
      auth:
        tokenSecretRef:
          name: {{ .Values.eso.tokenSecret }}
          key: token
          namespace: {{ .Values.vault.global.namespace }}
{{- end }}
