
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .Values.eso.tokenSecret }}
# #   namespace: {{ .Values.vault.global.namespace }}
#   namespace: vault-namespace

# stringData:
#   token: "root"
