// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user/usecases/users_usecaseses.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "rest-api/internal/models"
	common_utils "rest-api/internal/shared/common_utils"

	gomock "github.com/golang/mock/gomock"
)

// MockUserUseCasesI is a mock of UserUseCasesI interface.
type MockUserUseCasesI struct {
	ctrl     *gomock.Controller
	recorder *MockUserUseCasesIMockRecorder
}

// MockUserUseCasesIMockRecorder is the mock recorder for MockUserUseCasesI.
type MockUserUseCasesIMockRecorder struct {
	mock *MockUserUseCasesI
}

// NewMockUserUseCasesI creates a new mock instance.
func NewMockUserUseCasesI(ctrl *gomock.Controller) *MockUserUseCasesI {
	mock := &MockUserUseCasesI{ctrl: ctrl}
	mock.recorder = &MockUserUseCasesIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUseCasesI) EXPECT() *MockUserUseCasesIMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserUseCasesI) CreateUser(ctx context.Context, user *models.User) []common_utils.ErrorResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].([]common_utils.ErrorResponse)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserUseCasesIMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserUseCasesI)(nil).CreateUser), ctx, user)
}

// DeleteUser mocks base method.
func (m *MockUserUseCasesI) DeleteUser(ctx context.Context, id int64) []common_utils.ErrorResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].([]common_utils.ErrorResponse)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserUseCasesIMockRecorder) DeleteUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserUseCasesI)(nil).DeleteUser), ctx, id)
}

// GetAllUsers mocks base method.
func (m *MockUserUseCasesI) GetAllUsers(ctx context.Context, params models.FilterParams) ([]models.User, []common_utils.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx, params)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].([]common_utils.ErrorResponse)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockUserUseCasesIMockRecorder) GetAllUsers(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockUserUseCasesI)(nil).GetAllUsers), ctx, params)
}

// GetUser mocks base method.
func (m *MockUserUseCasesI) GetUser(ctx context.Context, id int64) (models.User, []common_utils.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].([]common_utils.ErrorResponse)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserUseCasesIMockRecorder) GetUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserUseCasesI)(nil).GetUser), ctx, id)
}

// UpdateUser mocks base method.
func (m *MockUserUseCasesI) UpdateUser(ctx context.Context, user models.User) []common_utils.ErrorResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].([]common_utils.ErrorResponse)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserUseCasesIMockRecorder) UpdateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserUseCasesI)(nil).UpdateUser), ctx, user)
}
