// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user/service/users_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "rest-api/internal/models"
	commonutils "rest-api/internal/shared/common_utils"

	gomock "github.com/golang/mock/gomock"
)

// MockUserServiceI is a mock of UserServiceI interface.
type MockUserServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceIMockRecorder
}

// MockUserServiceIMockRecorder is the mock recorder for MockUserServiceI.
type MockUserServiceIMockRecorder struct {
	mock *MockUserServiceI
}

// NewMockUserServiceI creates a new mock instance.
func NewMockUserServiceI(ctrl *gomock.Controller) *MockUserServiceI {
	mock := &MockUserServiceI{ctrl: ctrl}
	mock.recorder = &MockUserServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceI) EXPECT() *MockUserServiceIMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserServiceI) CreateUser(ctx context.Context, user *models.User) []commonutils.ErrorResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].([]commonutils.ErrorResponse)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceIMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserServiceI)(nil).CreateUser), ctx, user)
}

// DeleteUser mocks base method.
func (m *MockUserServiceI) DeleteUser(ctx context.Context, id int64) []commonutils.ErrorResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].([]commonutils.ErrorResponse)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceIMockRecorder) DeleteUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserServiceI)(nil).DeleteUser), ctx, id)
}

// GetAllUsers mocks base method.
func (m *MockUserServiceI) GetAllUsers(ctx context.Context, params models.FilterParams) ([]models.User, []commonutils.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx, params)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].([]commonutils.ErrorResponse)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockUserServiceIMockRecorder) GetAllUsers(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockUserServiceI)(nil).GetAllUsers), ctx, params)
}

// GetUser mocks base method.
func (m *MockUserServiceI) GetUser(ctx context.Context, id int64) (models.User, []commonutils.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].([]commonutils.ErrorResponse)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserServiceIMockRecorder) GetUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserServiceI)(nil).GetUser), ctx, id)
}

// UpdateUser mocks base method.
func (m *MockUserServiceI) UpdateUser(ctx context.Context, user models.User) []commonutils.ErrorResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].([]commonutils.ErrorResponse)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServiceIMockRecorder) UpdateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserServiceI)(nil).UpdateUser), ctx, user)
}
