name: Go Tests
on: [push, pull_request,workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      # Run tests inside REST-API and put coverage file at repo root
      - run: |
          cd REST-API
          go test ./... -coverprofile=../coverage.out

      - uses: codecov/codecov-action@v4
        with:
          files: coverage.out     # now the file is at the root
